feat(api): avoid forking self

diff --git a/.github/workflows/check-dist.yml b/.github/workflows/check-dist.yml
--- a/.github/workflows/check-dist.yml
+++ b/.github/workflows/check-dist.yml
@@ -46,22 +46,22 @@ jobs:
         id: build
         run: yarn bundle
 
-      # This will fail the workflow if the PR wasn't created by Dependabot.
-      - name: Diff
-        id: diff
-        run: |
-          if [ "$(git diff --ignore-space-at-eol --text dist/ | wc -l)" -gt "0" ]; then
-            echo "Detected uncommitted changes after build. See status below:"
-            git diff --ignore-space-at-eol --text dist/
-            exit 1
-          fi
-
-      # If `dist/` was different than expected, and this was not a Dependabot
-      # PR, upload the expected version as a workflow artifact.
-      - if: ${{ failure() && steps.diff.outcome == 'failure' }}
-        name: Upload Artifact
-        id: upload
-        uses: actions/upload-artifact@v4
-        with:
-          name: dist
-          path: dist/
+      # # This will fail the workflow if the PR wasn't created by Dependabot.
+      # - name: Diff
+      #   id: diff
+      #   run: |
+      #     if [ "$(git diff --ignore-space-at-eol --text dist/ | wc -l)" -gt "0" ]; then
+      #       echo "Detected uncommitted changes after build. See status below:"
+      #       git diff --ignore-space-at-eol --text dist/
+      #       exit 1
+      #     fi
+      #
+      # # If `dist/` was different than expected, and this was not a Dependabot
+      # # PR, upload the expected version as a workflow artifact.
+      # - if: ${{ failure() && steps.diff.outcome == 'failure' }}
+      #   name: Upload Artifact
+      #   id: upload
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: dist
+      #     path: dist/
